import React, { useRef } from 'react';
function SBCQ() {
    const questions = [
        {
          id:1,
          question: "A train 120 meters long is running with a speed of 60 km/hr. In what time will it pass a boy who is running at 6 km/hr in the direction opposite to that in which the train is going?",
          options: ['5m/s', '9m/s', '8m/s', '4m/s'],
          correctIndex: 2,
          ref: useRef(null),
        },
        {
          id:2,
          question: "Two friends shayam and Kailash own two versions of a car. Shayam owns the diesel version of the car, while kailash owns the petrol version. Kailash's car gives an average that is 20% higher than Shayam's (in terms of litres per kilometre). It is known that petrol costs 60% of its price higher than diesel.The ratio of the cost per kilometer of kailash's car to shayam's car is ?",
          options: ['3:1', '1:3', '1:2', '2:1'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:3,
          question: "In the product of two fractional values 13/425 and 17/1625. How many zeros are there between the decimal point and the first non-zero digit after the decimal point?",
          options: ['3','4', '5', '6'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:4,
          question: "Arjun, Ankit, and Anil can complete a task in 40 days, 50 days, and 64 days respectively. Amar is twice as efficient as Arjun. All of them worked together for five days. Then, Arjun and Anil worked together for a few days alone completed the task. If Amar was paid Rs. 1920 for his work, how much was Anil paid for his work?",
          options: ['3840', '960', '1920', '640'],
          correctIndex: 2,
          ref: useRef(null),
        },
        {
          id:5,
          question: "The ratio of balls in three boxes is 6:8:9 In what ratio should the balls in the second and third boxes be increased, So that the final ratio becomes 1:3:4?",
          options: ['3:9', '30:40', '2:3', '24:45'],
          correctIndex: 2,
          ref: useRef(null),
        },
        {
          id:6,
          question: "The average price of 16 pens is Rs. 64 while the average price of 14 of these pens is Rs. 44. Of the remaining two pens, if the price of one pen is 40% more than the other, what is the price of each of these two pens?",
          options: ['250,238', '170,238', '160,238', '170,248'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:7,
          question: "At what Percentage above the cost price must an article be marked, so as to gain 33% after allowing the customer a discount of 5%",
          options: ['33%', '45%', '40%', '51%'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:8,
          question: "Anuj, Bibhuti and Chandu can lay 432 m of wires together in 8 days. In a day, Chandu can lay as many more meters of wire than Bibhuti as Bibhuti can lay more than Anuj. Chandu's 5 days of work is equivalent to Anuj's 7 days of work. How many meters of wire can Anuj alone lay in a day?",
          options: ['12', '15', '17', '20'],
          correctIndex: 1,
          ref: useRef(null),
        },
        {
          id:9,
          question: "Read the following information carefully and answer the questions given below: 1.P, Q, R, S, T, U and V are sitting around a circular table facing the centre.  2.R is next to the left of U and V is second to the left of R. 3.P is sitting third to the left of T. 4.Q is between S and T. Which of the following is false?",
          options: ['P is fourth to the right is T', 'U is to the immediate right of R', 'U is the third to the right of S', 'Q is to the immediate left of S'],
          correctIndex: 2,
          ref: useRef(null),
        },
        {
          id:10,
          question: "1. A3P means A is the mother of P.2. A4P means A is the brother of P. 3. A9P means A is the husband of P. 4. ASP means A is the daughter of P. Which of the following means that K is the mother-in-law of M?",
          options: [' M9N3K4J', 'M9N5K3J', 'K5J9M3N', 'K3J9N4M'],
          correctIndex: 1,
          ref: useRef(null),
        },
        {
          id:11,
          question: "Megha walks 7 km towards East and then she takes a U-turn and comes 12 km back. She then takes a left turn and walks 3 Km; the she again takes a left turn and after walking for 5 km she again takes a left turn and walks for 2 more km. How far she is from the point she started?",
          options: ['1Km', '2km', '3km', '0km'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:12,
          question: "If the sum of squares of two numbers is 2754 and their HCF and LCM are 9 and 135 respectively, then the numbers are?",
          options: ['27,36', '27,35', '28,45', '27,45'],
          correctIndex: 3,
          ref: useRef(null),
        },
        {
          id:13,
          question: "Rohan's present age is two-fifth of the age of his elder sister Radha. After 7 years, he will be two-third of the age of Radha. How old is the Radha at present (in years)?",
          options: ['11', '8.75', '9', '7.50'],
          correctIndex: 1,
          ref: useRef(null),
        },
        {
          id:14,
          question: "Grace is twice as efficient as Garry and Garry is thrice as efficient as Guna, who can finish a job alone in 24 days. If Grace, Garry and Guna work on alternate days with Garry starting first, in how many days will the job finish?",
          options: ['5', '6', '7', '8'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:15,
          question: "Rohit Sharma played well this season, his current batting average is 38. If he scores 78 runs in today's match his batting average will become 42, how many matches has he played in this season?",
          options: ['8', '10', '9', '6'],
          correctIndex: 1,
          ref: useRef(null),
        },{
          id:16,
          question: "Two brothers Abhishek (A) and Bandhan (B) start running from a common point. Abhishek goes 20 km towards North-East whereas Bandhan goes 16 km towards East and then 12 km towards North. How far are A and B from each other?",
          options: ['64', '81', '27', 'None'],
          correctIndex: 3,
          ref: useRef(null),
        },
        {
          id:17,
          question: "If the letters of the word CHASM are rearranged to form 5 letter words such that none of the word repeat and the results arranged in ascending order as in a dictionary what is the rank of the word CHASM?",
          options: ['36', '32', '30', '28'],
          correctIndex: 1,
          ref: useRef(null),
        },
        {
          id:18,
          question: "A car of length 4m wants to overtake a trailer truck of length 20m travelling at 36 km/hr within 10 seconds. At what speed should the car travel?",
          options: ['12.4 m/s', '15.4 m/s', '13.5 m/s', '20.5 m/s'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:19,
          question: "If a, b, c are distinct positive integers, what is the highest value a * b * c can take if a+b+c=31?",
          options: ['1055', '1100', '1080', '1200'],
          correctIndex: 2,
          ref: useRef(null),
        },
        {
          id:20,
          question: " Raj was given a task to arrange the letters of the word SWITZERLAND. In how many ways can he arrange the letters of the word SWITZERLAND so that the positions of the vowels are used by vowels only and positions of the consonants are used by the consonants only??",
          options: ['11!/8!', '11!/(3!*8!)', '3!*8!', '11!/3!'],
          correctIndex: 2,
          ref: useRef(null),
        },
        {
          id:21,
          question: "If a man is given 5 numerical digits and 4 alphabets, how many alphanumeric words can be form using exactly 2 digits and 3 alphabets?",
          options: ['240', '6000', '3600', '4800'],
          correctIndex: 3,
          ref: useRef(null),
        },
        {
          id:22,
          question: "There are 25 people in a group. If all shake hands with one another. How many handshakes are possible?",
          options: ['300', '25!', '24!+1', '600'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:23,
          question: "If 13:11 is the ratio of the present age of Arijit Singh and Sonu Nigam respectively and 15:9 is the ratio between Arijit's age 4 years hence and Sonu's age 4 years ago. Then what will be the ratio of Arijit's age 4 years ago and Sonu's age 4 years hence?",
          options: ['13:9', '11:7', '11:13', '9:15'],
          correctIndex: 2,
          ref: useRef(null),
        },
        {
          id:24,
          question: "The average weight of 5 people's increases by 3 kg when a new person comes in place of one of them weighing 30 kg. What might be the weight of the new person?",
          options: ['55kg', '45kg', '65kg', '35kg'],
          correctIndex: 1,
          ref: useRef(null),
        },
        {
          id:25,
          question: "In a code language UNIQUE is written down as DTPHMT. Then how FRIEND will be written on the basis of the same code language?",
          options: ['DNEIRF', 'CMDHQE', 'CMDHUE', 'DMCHEU'],
          correctIndex: 1,
          ref: useRef(null),
        },
        {
          id:26,
          question: "Anita walked 10 Km in the east direction. She then turned right and walked for 3 Km. Again, she took a right turn and walked for 14 Km. How far is she from the point she started?",
          options: ['5', '6', '7', '8'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:27,
          question: "A contractor undertakes to do a piece of work in 40 days. He engages 100 men at the beginning and 100 more after 35 days and completes the work in stipulated time. If he had not engaged the additional men, how many days behind schedule would it be finished?",
          options: ['4', '6', '5', '2'],
          correctIndex: 2,
          ref: useRef(null),
        },
        {
          id:28,
          question: "By selling an article for Rs. 144, a man gained such that the percentage gain equals the cost price. The C.P. of the article is?",
          options: ['60', '80', '84', '96'],
          correctIndex: 1,
          ref: useRef(null),
        },
        {
          id:29,
          question: "The salaries of Ritika and Shivam are in the ratio 2:3. If the salary of each is increased by Rs. 4000, the new ratio becomes 40:57. What is Shivam's present salary?",
          options: ['38000', '29000', '30000', '39800'],
          correctIndex: 0,
          ref: useRef(null),
        },
        {
          id:30,
          question: "A and B invest in a business in the ratio 3:2. If 5% of the total profit goes to charity and A's share is Rs. 855, the total profit is?",
          options: ['1200', '1800', '1400', '1500'],
          correctIndex: 3,
          ref: useRef(null),
        }
      ];
  return questions;
}

export default SBCQ;
